=== med-united/epa4all/api-xds/src/main/resources/ig-schema/ig-schema-definition.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$ref": "#/definitions/StructureDefinition",
	"$version": "1.2.2",
	"definitions": {
		"CardinalityDefinition": {
			"description": "Constraints on the amount of the XDS folder or document in order to support that structured document in the electronic health record system.",
			"type": "object",
			"properties": {
				"min": {
					"type": "string"
				},
				"max": {
					"type": "string"
				},
				"unique": {
					"description": "The value 'true' means that solely one document/folder with the availablility status 'approved' is allowed to be registered with the given metadata combination. False means that multiple instances may be submitted.",
					"type": "boolean"
				}
			},
			"required": [
				"min",
				"max"
			],
			"additionalProperties": false
		},
		"FolderDefinition": {
			"type": "object",
			"properties": {
				"name": {
					"type": "string"
				},
				"value": {
					"anyOf": [
						{
							"title": "value",
							"type": "object",
							"properties": {
								"code": {
									"type": "string"
								},
								"codeSystem": {
									"type": "string"
								},
								"displayName": {
									"type": "string"
								},
								"deprecatedFrom": {
									"description": "The following value is deprecated and should not be used from this date on. Useage of alternative value with same name instead is recommended",
									"type": "string",
									"format": "date"
								},
								"desc": {
									"$ref": "#/definitions/DescriptionDefinition"
								}
							},
							"required": [
								"code",
								"codeSystem",
								"displayName"
							],
							"additionalProperties": false
						},
						{
							"title": "value",
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"code": {
										"type": "string"
									},
									"codeSystem": {
										"type": "string"
									},
									"displayName": {
										"type": "string"
									},
									"deprecatedFrom": {
										"description": "The following value is deprecated and should not be used from this date on. Usage of alternative value with same name instead is recommended.",
										"type": "string",
										"format": "date"
									},
									"desc": {
										"$ref": "#/definitions/DescriptionDefinition"
									}
								},
								"required": [
									"code",
									"codeSystem",
									"displayName"
								],
								"additionalProperties": false
							}
						},
						{
							"title": "value",
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					]
				}
			},
			"required": [
				"name",
				"value"
			],
			"additionalProperties": false
		},
		"DescriptionDefinition": {
			"title": "desc",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"language": {
						"type": "string"
					},
					"#text": {
						"type": "string"
					}
				},
				"required": [
					"language",
					"#text"
				],
				"additionalProperties": false
			}
		},
		"DocumentDefinition": {
			"type": "object",
			"properties": {
				"version": {
					"description": "The version of the document format.",
					"type": "string"
				},
				"name": {
					"description": "The name of the specific document.",
					"type": "string"
				},
				"description": {
					"description": "The description of the specific document.",
					"type": "string"
				},
				"canonicalUrl": {
					"description": "A canonical URL of the structure definiton of the specific document.",
					"type": "string"
				},
				"metadata": {
					"title": "metadata",
					"type": "array",
					"items": {
						"$ref": "#/definitions/FolderDefinition"
					}
				},
				"documentCardinality": {
					"$ref": "#/definitions/CardinalityDefinition"
				},
				"implementationArtifact": {
					"description": "This usage specification is not intended for verifying structured documents.",
					"type": "boolean"
				},
				"maxDocumentHistory": {
					"description": "Defines the maximum amount of deprecated elements to be kept in a XDS RPLC chain (approved document does not count). Oldest entries may be deleted when this limit gets exeeded",
					"type": "integer"
				}
			},
			"required": [
				"name",
				"description",
				"metadata",
				"documentCardinality"
			],
			"additionalProperties": false
		},
		"StructureDefinition": {
			"type": "object",
			"properties": {
				"name": {
					"description": "The technical name of the structured document.",
					"type": "string"
				},
				"description": {
					"description": "The overall description of the structured document.",
					"type": "string"
				},
				"igVersion": {
					"description": "Version information of the Implementation Guideline file",
					"type": "string"
				},
				"guidelineDefinition": {
					"description": "A link to the (FHIR) implementation guideline including its version.",
					"type": "object",
					"properties": {
						"url": {
							"type": "string",
							"format": "uri"
						},
						"version": {
							"type": "string"
						}
					},
					"required": [
						"url"
					],
					"additionalProperties": false
				},
				"folderCardinality": {
					"$ref": "#/definitions/CardinalityDefinition"
				},
				"validFromDate": {
					"description": "Date from which the structured document is accepted (upload/download) by ePA-server.",
					"type": "string",
					"format": "date"
				},
				"clientReadOnlyFromDate": {
					"description": "Date from which the structured document is accepted (only download) by ePA-server. The upload is rejected by ePA-server",
					"type": "string",
					"format": "date"
				},
				"type": {
					"description": "The collection type of the structured document - either 'mixed' or 'uniform'.",
					"type": "string"
				},
				"metadata": {
					"$ref": "#/definitions/FolderDefinition"
				},
				"elements": {
					"type": "array",
					"items": {
						"$ref": "#/definitions/DocumentDefinition"
					}
				}
			},
			"required": [
				"name",
				"description",
				"guidelineDefinition",
				"validFromDate",
				"elements"
			]
		}
	}
}

=== med-united/epa4all/api-xds/src/main/resources/ig-schema/ig-mothersrecord_V_1_1_0.json
{
	"name": "Maternity Records",
	"description": "Maternity Records defined as a medical information object (MIO) by KBV.",
	"igVersion": "3.0.0",
	"guidelineDefinition": {
		"url": "https://mio.kbv.de/display/MP1X0",
		"version": "1.1.0"
	},
	"folderCardinality": {
		"min": "0",
		"max": "n",
		"unique": false
	},
	"validFromDate": "2022-03-31",
	"type": "uniform",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "pregnancy_childbirth",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Schwangerschaft und Geburt",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten gemäß der nach § 92 Absatz 1 Satz 2 Nummer 4 in Verbindung mit den §§ 24c bis 24f beschlossenen Richtlinie des Gemeinsamen Bundesausschusses über die ärztliche Betreuung während der Schwangerschaft und nach der Entbindung (elektronischer Mutterpass) sowie Daten, die sich aus der Versorgung der Versicherten mit Hebammenhilfe ergeben."
				}
			]
		}
	},
	"elements": [
		{
			"version": "1.1.0",
			"name": "KBV_PR_MIO_MR_Bundle",
			"description": "This document is of FHIR resource type KBV_PR_MIO_MR_Bundle.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_MR_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "GEBU",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Schwangerschafts- und Geburtsdokumentation",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumente mit allen Informationen über die Phase vor, während und nach dem Geburtsverlauf, inklusive Funktionsdiagnostik (z.B. CTG) und Bildgebende Diagnostik und ähnliche Befunde die sich auf das Kind beziehen. Weiterhin beinhalten das Konzept Belege zur Neugeborenversorgung, wenn sie der Akte der Mutter zugeordnet sind. Verordnungen und Medikamentationsdokumentation hingegen werden über die jeweiligen Konzepte (VERO und MEDI) abgebildet. Beispiele: Geburtenbericht, Geburtenprotokoll, Geburtenverlaufskurve, Neugeborenenscreening, Partogramm, Wiegekarte, Neugeborenendokumentationsbogen, Säuglingskurve, Stillprotokoll"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:Mutterpass:v1.1.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Mutterpass (gematik)"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n",
				"unique": false
			}
		}
	]
}

=== med-united/epa4all/api-xds/src/main/resources/ig-schema/ig-dmp_copd_V_4.json
{
	"name": "eDMP-Datensatz COPD",
	"description": "Indikationsspezifischer Datensatz für das strukturierte Behandlungsprogramm Chronisch obstruktive Lungenerkrankung (COPD)",
	"igVersion": "3.0.0",
	"guidelineDefinition": {
		"url": "https://update.kbv.de/ita-update/Medizinische-Dokumentationen/COPD/"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2023-01-01",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "other",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "in andere Kategorien nicht einzuordnende Dokumente, eDMPs sowie Telemedizinisches Monitoring",
			"desc": [
				{
					"language": "de-DE",
					"#text": "sonstige von den Leistungserbringern für den Versicherten bereitgestellte Daten, insbesondere Daten, die sich aus der Teilnahme des Versicherten an strukturierten Behandlungsprogrammen bei chronischen Krankheiten gemäß § 137f ergeben"
				}
			]
		}
	},
	"elements": [
		{
			"name": "eDMP record for chronic obstrusive pulmonary disease",
			"description": "This document is an HL7 CDA-based document.",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "BRI",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Brief",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Alle Varianten von Arztbriefen wie Überweisungsbrief, Entlassbrief, etc. sowie weitere zusammenfassende Dokumente mit einer ärztlichen oder pflegerischen Bewertung der Fakten. Befundberichte werden über das Konzept BEF (Befundbericht) abgedeckt"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "FPRO",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Therapiedokumentation",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumentation zur Durchführung von Therapien, durch ärztliche und nicht-ärztliche Therapeuten. Auch die zugehörigen Therapieanforderungen werden mit diesem Konzept abgebildet. Bei fachspezifischen Dokumententypen wie Bestrahlungsprotokollen, sollte stattdessen das spezifischere Konzept verwendet werden, z.B. BSTR (Bestrahlungsdokumentation), OPDK (OP-Dokumente). Reine Dokumentation der Medikation wird durch das Konzept MEDI (Medikamentöse Therapien) abgebildet. Beispiele: Ergotherapieprotokoll, Logopädieprotokoll, Physiotherapieprotokoll, Schmerztherapieprotokoll, Reanimationsprotokoll, Dialysedokumente, Psychotherapeutische Dokumente"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:DMP-COPD:v4",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "eDMP Chronic Obstrusive Pulmonary Disease (gematik)"
					}
				},
				{
					"name": "documentEntry.eventCodeList",
					"value": {
						"code": "06",
						"codeSystem": "1.2.276.0.76.5.223",
						"displayName": "COPD"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/hl7-v3"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}

=== med-united/epa4all/api-xds/src/main/resources/ig-schema/ig-childsrecord.json
{
	"name": "Child Medical Records",
	"description": "Child medical records defined as a medical information object (MIO) by KBV. It may include participation card and parental notes.",
	"igVersion": "3.0.0",
	"guidelineDefinition": {
		"url": "https://mio.kbv.de/display/UH1X0/U-Heft",
		"version": "1.1.0"
	},
	"folderCardinality": {
		"min": "1",
		"max": "1",
		"unique": true
	},
	"validFromDate": "2021-05-05",
	"type": "mixed",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "child",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "Kinderuntersuchungsheft",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten gemäß der nach § 92 Absatz 1 Satz 2 Nummer 3 und Absatz 4 in Verbindung mit § 26 beschlossenen Richtlinie des Gemeinsamen Bundesausschusses zur Früherkennung von Krankheiten bei Kindern (elektronisches Untersuchungsheft für Kinder)"
				}
			]
		}
	},
	"elements": [
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_CMR_Bundle",
			"description": "This document is a child medical record.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_CMR_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "BERI",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Arztberichte",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ärztliche Zusammenfassungen und Verlaufsbeurteilungen von Behandlungsepisoden, Epikrisen und Abschlussberichte zu stationären oder ambulanten Behandlungsfällen. Beispiele: Arztbrief, Entlassungsbericht, Ärztliche Stellungnahme, Durchgangsarztbericht / BG-Bericht, Rehabericht, Verlegungsbericht, vorläufiger Arztbericht, ärztlicher Verlaufsbericht, Ambulanzbericht"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:KinderuntersuchungsheftUntersuchungen:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Untersuchungen Kinderuntersuchungsheft"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n",
				"unique": false
			}
		},
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_PC_Bundle",
			"description": "This document is a participation card.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_PC_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "BESC",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Ärztliche Bescheinigungen",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Bestätigung eines Arztes über einen bestimmten, patientenbezogenen Sachverhalt. Beispiele: Arbeitsunfähigkeitsbescheinigung, Beurlaubung, Todesbescheinigung, Ärztliche Bescheinigung, Notfall-/ Vertretungsschein"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:KinderuntersuchungsheftTeilnahmekarte:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Teilnahmekarte Kinderuntersuchungsheft"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pkcs7-mime"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n",
				"unique": false
			}
		},
		{
			"version": "1.0.0",
			"name": "KBV_PR_MIO_PN_Bundle",
			"description": "This document holds parental notes.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_PN_Bundle",
			"metadata": [
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "AUS",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Medizinischer Ausweis",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Ausweise, Pässe und ähnliche kurze Datensätze, die wichtige medizinische Informationen zusammenfassen. Beispiele: Allergiepass, Allergieausweis, Impfpass, Impfausweis, Impfbuch, Notfalldatensatz"
							}
						]
					}
				},
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "PATD",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Patienteneigene Dokumente",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumente, welche der Patient zu seinem Kontakt in der Gesundheitseinrichtung mitbringt, die aber nicht in unmittelbarem Zusammenhang mit dem aktuellen Kontakt stehen müssen. Sowie Dokumente, in denen das mitgebrachte Patienteneigentum festgehalten wird. Beispiele: Ausweise, Vorsorgevollmacht, Patientenverfügung, Wertgegenständeverwaltung, Notfalldatensatz, Patiententagebuch"
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:KinderuntersuchungsheftNotizen:v1.0.0",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "Notizen Kinderuntersuchungsheft"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml"
					]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			}
		}
	]
}

=== med-united/epa4all/api-xds/src/main/resources/ig-schema/ig-diga_V_1_1.json
{
	"name": "DiGA Toolkit",
	"description": "DiGA Toolkit defined as a medical information object (MIO) by KBV.",
	"igVersion": "1.0.0",
	"guidelineDefinition": {
		"url": "https://mio.kbv.de/display/DIGA1X1X0",
		"version": "1.1"
	},
	"folderCardinality": {
		"min": "0",
		"max": "n",
		"unique": false
	},
	"validFromDate": "2023-07-01",
	"type": "uniform",
	"metadata": {
		"name": "folder.codeList",
		"value": {
			"code": "diga",
			"codeSystem": "1.2.276.0.76.5.512",
			"displayName": "DiGA",
			"desc": [
				{
					"language": "de-DE",
					"#text": "Daten des Versicherten aus digitalen Gesundheitsanwendungen des Versicherten nach § 33a."
				}
			]
		}
	},
	"elements": [
		{
			"version": "1.1",
			"name": "KBV_PR_MIO_DIGA_Bundle",
			"description": "This document is of FHIR resource type KBV_PR_MIO_DIGA_Bundle.",
			"canonicalUrl": "https://fhir.kbv.de/StructureDefinition/KBV_PR_MIO_DIGA_Bundle",
			"metadata": [
				{
					"name": "documentEntry.typeCode",
					"value": {
						"code": "PATD",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.9",
						"displayName": "Patienteneigene Dokumente",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Dokumente, welche der Patient zu seinem Kontakt in der Gesundheitseinrichtung mitbringt, die aber nicht in unmittelbarem Zusammenhang mit dem aktuellen Kontakt stehen müssen. Sowie Dokumente, in denen das mitgebrachte Patienteneigentum festgehalten wird.  Beispiele: Ausweise, Vorsorgevollmacht, Patientenverfügung, Wertgegenständeverwaltung, Notfalldatensatz, Patiententagebuch"
							}
						]
					}
				},
				{
					"name": "documentEntry.classCode",
					"value": {
						"code": "DUR",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.8",
						"displayName": "Durchführungsprotokoll",
						"desc": [
							{
								"language": "de-DE",
								"#text": "Maschinell oder von Menschen erstellte Protokolle durchgeführter Anamnese, Diagnostik oder Therapie, z.B. Anamnesebogen, OP-Berichte, Medikamentenverabreichungen; hierzu zählen auch ausgefüllte Checklisten die das prozesskonforme Vorgehen während einer Untersuchung oder OP dokumentieren. Die Protokolle können auch Handlungsanweisungen bzw. Empfehlungen beinhalten, z.B. Visitenprotokoll, Konsilbericht. Dazu gehören auch Messdaten (oft auch als Quelldaten oder Rohdaten bezeichnet) ohne menschliche Bewertung wie Temperaturkurven, Blutdruck-Messungen, Blutzuckerkurven, unbefundete EKGs, Herz-Tonaufnahmen, Bestrahlungsprotokoll, Dosiswerte, etc. mit Ausnahme von Bilddaten und Videodaten. Der Begriff 'Patientenkurve' wird in einigen Fällen für eine Sammlung von Temperatur-, Blutdruck- und weiteren pflegerischen Beobachtungen verwendet und sollte dann auch über das Konzept DUR ('Durchführungsprotokoll') abgedeckt werden. Da der Begriff 'Patientenkurve' auch für andere Dokumente (bzw. Dokumentenkombinationen) verwendet wird, sollte vor einer solchen Abbildung eine Analyse der so bezeichneten Dokumente durchgeführt und das entsprechende Konzept verwendet werden. Dokumente die mit diesem Konzept bezeichnet werden können maschinenlesbar sein, müssen es jedoch nicht (z.B. sowohl EKG-Kurve wie auch eingescanntes EKG sind abgedeckt). Ursprungs- und Zwischenformate (wie z.B. Diktat eines Arztbriefes) werden mit dem inhaltlich sinnvollen classCode gekennzeichnet (Brief in diesem Beispiel)."
							}
						]
					}
				},
				{
					"name": "documentEntry.formatCode",
					"value": {
						"code": "urn:gematik:ig:diga:v1.1",
						"codeSystem": "1.3.6.1.4.1.19376.3.276.1.5.6",
						"displayName": "DiGA (gematik) v1.1"
					}
				},
				{
					"name": "documentEntry.mimeType",
					"value": [
						"application/fhir+xml",
						"application/pdf"]
				}
			],
			"documentCardinality": {
				"min": "0",
				"max": "n"
			},
			"maxDocumentHistory" : 10
		}
	]
}
